### ISSUE TITLE
Modelo de Datos

### ISSUE THREAD

**Issue by ameliafb** [Arquisoft/InciDashboard_e3a#1]
En InciManager_e3a hay una primera versión del modelo de datos. Faltan entidades para operarios y para guardar la configuración de CM. Podeis coger la parte que hay (difiere un poco del esquema de tablas que os pasé, pero es para simplificar el jpa), aunque seguro que va cambiando según avancemos.
@espiguinho

**Comment by ameliafb** [comment]
En nuestro repositorio hay un modelo de datos funcionando, pasarlo a vuestro proyecto, faltaría cómo guardar la configuración del CM
@espiguinho 

(no puedo notificar aquí a Álvaro Glez.)

**Comment by espiguinho** [comment]
@AlvaroGonzalezC
